### ISSUE TITLE
Crash on xcode 11.5 On launch 

### ISSUE THREAD

**Issue by ahmedKhaledMohammed** [idnow/de.idnow.ios.sdk#17]
dyld: Symbol not found: _$s9Alamofire10HTTPMethodO3getyA2CmFWC
  Referenced from: /private/var/containers/Bundle/Application/1B50EBA6-1081-4E1D-9A2D-3FCA48E8E3A4/Demo.app/Frameworks/IDNowSDKCore.framework/IDNowSDKCore
  Expected in: /private/var/containers/Bundle/Application/1B50EBA6-1081-4E1D-9A2D-3FCA48E8E3A4/Demo.app/Frameworks/Alamofire.framework/Alamofire
 in /private/var/containers/Bundle/Application/1B50EBA6-1081-4E1D-9A2D-3FCA48E8E3A4/Demo.app/Frameworks/IDNowSDKCore.framework/IDNowSDKCore

**Comment by BilelSelmiIDnow** [comment]
@ahmedKhaledMohammed :  if you are using SDK 3.21.0, please do the following : Go to Pods, then under Targets look for Alamofire, OpenCV2, Sentry and Starscream, under Build Settings set Build Libraries for Distribution for the pods to Yes, Otherwise you’ll get dyld: Symbol not found error at runtime. This is in the documentation

**Comment by Jeadonara** [comment]
@BilelSelmiIDnow  Even I am trying to use version 4.9.0 and set Build Libraries for Distribution for the Sentry and OpenCV2 to Yes, I am getting dyld error at run time. Could you please help?
