### ISSUE TITLE
Access to previous builds

### ISSUE THREAD

**Issue by gyulavoros** [idnow/de.idnow.ios.sdk#9]
We are using Carthage to manage dependencies. Our CI pipeline is failing ATM because it seems older builds of the IDNowSDK are not available anymore:

```
GET /idnow/de.idnow.ios.sdk/master/IDNowSDKCore-Xcode-11.3.1.json HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: raw.githubusercontent.com
User-Agent: HTTPie/2.0.0

HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
...

{
    "3.20.0": "https://github.com/idnow/de.idnow.ios.sdk/releases/download/3.20.0-Xcode_11.3.1/IDNowSDKCore.framework.zip"
}
```

**Comment by BilelSelmiIDnow** [comment]
@gyulavoros : at the moment we are downloading the IDnow SDK framework binary with adding this to the Cartfile :  binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/IDNowSDKCore-Xcode-11.3.1.json" : where the .json contains the url to download the latest framework(For this example 3.20.1), if you want to download and earlier version you should add "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/3.20.0-Xcode_11.3.1/IDNowSDKCore-Xcode-11.3.1.json" (Tag version instead of master): here you can download version 3.20.0
